"""Initial migration - create users table

Revision ID: 4208d1c453c2
Revises: 
Create Date: 2025-05-22 21:20:28.809976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4208d1c453c2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_clients_cpf'), 'tb_clients', ['cpf'], unique=True)
    op.create_index(op.f('ix_tb_clients_email'), 'tb_clients', ['email'], unique=True)
    op.create_index(op.f('ix_tb_clients_id'), 'tb_clients', ['id'], unique=False)
    op.create_index(op.f('ix_tb_clients_name'), 'tb_clients', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_clients_name'), table_name='tb_clients')
    op.drop_index(op.f('ix_tb_clients_id'), table_name='tb_clients')
    op.drop_index(op.f('ix_tb_clients_email'), table_name='tb_clients')
    op.drop_index(op.f('ix_tb_clients_cpf'), table_name='tb_clients')
    op.drop_table('tb_clients')
    # ### end Alembic commands ###
