"""add products and product_images tables

Revision ID: 95d4e5e70c7a
Revises: 4208d1c453c2
Create Date: 2025-05-23 20:25:29.701589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95d4e5e70c7a'
down_revision: Union[str, None] = '4208d1c453c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('bar_code', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_products_id'), 'tb_products', ['id'], unique=False)
    op.create_index(op.f('ix_tb_products_name'), 'tb_products', ['name'], unique=True)
    op.create_index(op.f('ix_tb_products_sale_price'), 'tb_products', ['sale_price'], unique=False)
    op.create_table('tb_product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['tb_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_product_images_id'), 'tb_product_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_product_images_id'), table_name='tb_product_images')
    op.drop_table('tb_product_images')
    op.drop_index(op.f('ix_tb_products_sale_price'), table_name='tb_products')
    op.drop_index(op.f('ix_tb_products_name'), table_name='tb_products')
    op.drop_index(op.f('ix_tb_products_id'), table_name='tb_products')
    op.drop_table('tb_products')
    # ### end Alembic commands ###
