"""add role field to tb_clients

Revision ID: 9a34460daaf5
Revises: 5ac3b0a35903
Create Date: 2025-05-25 00:19:52.035423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a34460daaf5'
down_revision: Union[str, None] = '5ac3b0a35903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_clients', sa.Column('role', sa.Enum('USER', 'ADMIN', name='role_enum', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_clients', 'role')
    # ### end Alembic commands ###
