"""remove unique constraint from name

Revision ID: e7267dd2023e
Revises: 4fb1fca5c297
Create Date: 2025-05-26 10:24:02.594599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7267dd2023e'
down_revision: Union[str, None] = '4fb1fca5c297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tb_clients_name', table_name='tb_clients')
    op.create_index(op.f('ix_tb_clients_name'), 'tb_clients', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_clients_name'), table_name='tb_clients')
    op.create_index('ix_tb_clients_name', 'tb_clients', ['name'], unique=True)
    # ### end Alembic commands ###
